# Generated by Django 2.1.3 on 2018-12-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoothsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_packages', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=255)),
                ('additional_options', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city_or_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('office_phone_number', models.CharField(max_length=88)),
                ('direct_phone_number', models.CharField(max_length=88)),
                ('facebook_link', models.URLField(max_length=255)),
                ('website_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShowsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Toronto', 'Toronto'), ('Winnipeg', 'Winnipeg'), ('Calgary', 'Calgary'), ('Edmonton', 'Edmonton')], max_length=255)),
                ('fair_dates', models.CharField(choices=[('jun1', 'June 1st'), ('july2', 'July 2nd'), ('august3', 'August 3rd'), ('september4', 'September 4th')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='boothsmodel',
            name='associated_fair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.ShowsModel'),
        ),
    ]
