# Generated by Django 2.1.3 on 2018-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerFormModel',
            new_name='CustomerModelForm',
        ),
        migrations.RemoveField(
            model_name='boothsmodel',
            name='associated_fair',
        ),
        migrations.DeleteModel(
            name='BoothsModel',
        ),
        migrations.DeleteModel(
            name='ShowsModel',
        ),
    ]
