# Generated by Django 2.1.3 on 2018-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20181207_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodelform',
            name='direct_phone_number',
            field=models.CharField(blank=True, max_length=88),
        ),
        migrations.AlterField(
            model_name='customermodelform',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customermodelform',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=88),
        ),
        migrations.AlterField(
            model_name='customermodelform',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customermodelform',
            name='website_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
