# Generated by Django 2.1.5 on 2019-01-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0002_auto_20190129_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calgaryfair',
            name='calgary_options',
        ),
        migrations.RemoveField(
            model_name='edmontonfair',
            name='edmonton_booth_options',
        ),
    ]
