# Generated by Django 2.1.5 on 2019-02-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0006_auto_20190204_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calgaryfair',
            old_name='calgary_venue_option',
            new_name='calgary_venue_options',
        ),
    ]
