# Generated by Django 2.1.5 on 2019-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0007_auto_20190204_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torontofair',
            name='related_sale',
        ),
    ]
