# Generated by Django 2.1.5 on 2019-02-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfcapp', '0007_auto_20190204_1844'),
        ('fairs', '0008_remove_torontofair_related_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='torontofair',
            name='related_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfcapp.SalesFormData'),
        ),
    ]
