# Generated by Django 2.1.5 on 2019-02-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0013_auto_20190211_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='calgaryfair',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calgaryfair',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edmontonfair',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edmontonfair',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
