# Generated by Django 2.1.5 on 2019-02-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0014_auto_20190211_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calgaryfair',
            name='venue_options',
        ),
        migrations.RemoveField(
            model_name='edmontonfair',
            name='venue_options',
        ),
    ]
