# Generated by Django 2.1.5 on 2019-02-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0016_auto_20190212_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsitecontacts',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
