# Generated by Django 2.1.5 on 2019-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0022_auto_20190214_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='contact_calgary',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='contact_edmonton',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='contact_toronto',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='contact_winnipeg',
        ),
        migrations.RemoveField(
            model_name='calgaryfair',
            name='contact',
        ),
        migrations.AddField(
            model_name='calgaryfair',
            name='contact',
            field=models.ManyToManyField(blank=True, to='fairs.OnSiteContacts'),
        ),
        migrations.RemoveField(
            model_name='edmontonfair',
            name='contact',
        ),
        migrations.AddField(
            model_name='edmontonfair',
            name='contact',
            field=models.ManyToManyField(blank=True, to='fairs.OnSiteContacts'),
        ),
        migrations.RemoveField(
            model_name='torontofair',
            name='contact',
        ),
        migrations.AddField(
            model_name='torontofair',
            name='contact',
            field=models.ManyToManyField(blank=True, to='fairs.OnSiteContacts'),
        ),
        migrations.RemoveField(
            model_name='winnipegfair',
            name='contact',
        ),
        migrations.AddField(
            model_name='winnipegfair',
            name='contact',
            field=models.ManyToManyField(blank=True, to='fairs.OnSiteContacts'),
        ),
    ]
