# Generated by Django 2.1.5 on 2019-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0023_auto_20190214_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsitecontacts',
            name='calgary_fairs',
            field=models.ManyToManyField(blank=True, to='fairs.CalgaryFair'),
        ),
        migrations.AddField(
            model_name='onsitecontacts',
            name='edmonton_fairs',
            field=models.ManyToManyField(blank=True, to='fairs.EdmontonFair'),
        ),
        migrations.AddField(
            model_name='onsitecontacts',
            name='toronto_fairs',
            field=models.ManyToManyField(blank=True, to='fairs.TorontoFair'),
        ),
        migrations.AddField(
            model_name='onsitecontacts',
            name='winnipeg_fairs',
            field=models.ManyToManyField(blank=True, to='fairs.WinnipegFair'),
        ),
    ]
