# Generated by Django 2.1.5 on 2019-02-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0024_auto_20190214_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='calgary_fairs',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='edmonton_fairs',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='toronto_fairs',
        ),
        migrations.RemoveField(
            model_name='onsitecontacts',
            name='winnipeg_fairs',
        ),
    ]
