# Generated by Django 2.1.5 on 2019-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0026_auto_20190220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torontofair',
            name='discount_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='torontofair',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
