# Generated by Django 2.1.5 on 2019-02-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0027_auto_20190220_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='torontofair',
            name='tax_to_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
