# Generated by Django 2.1.5 on 2019-02-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0031_auto_20190221_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edmontonfair',
            name='additional_breakfast_option',
        ),
    ]
