# Generated by Django 2.1.5 on 2019-02-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0033_calgaryfair_wifi_for_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calgaryfair',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='edmontonfair',
            name='wifi',
        ),
        migrations.AddField(
            model_name='edmontonfair',
            name='wifi_for_device',
            field=models.CharField(default='-', max_length=400),
        ),
    ]
