# Generated by Django 2.1.5 on 2019-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0036_auto_20190321_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calgaryfair',
            name='additional_booth_option',
        ),
        migrations.RemoveField(
            model_name='edmontonfair',
            name='additional_booth_option',
        ),
        migrations.RemoveField(
            model_name='torontofair',
            name='additional_booth_option',
        ),
        migrations.RemoveField(
            model_name='winnipegfair',
            name='additional_booth_option',
        ),
    ]
