from cfcapp.models import SalesFormData
from django.db import models

class TorontoFair(models.Model):
    related_sale = models.ForeignKey(SalesFormData, on_delete=models.SET_NULL, null=True)
    toronto_dates = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    toronto_booth_options = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    toronto_date_1 = models.CharField(max_length=400, blank=True, default='-')
    toronto_date_2 = models.CharField(max_length=400, blank=True, default='-')
    toronto_additional_booth_option_1 = models.CharField(max_length=400, default='-')
    toronto_additional_booth_option_2 = models.CharField(max_length=400, default='-')

class CalgaryFair(models.Model):
    related_sale = models.ForeignKey(SalesFormData, on_delete=models.SET_NULL, null=True)
    calgary_dates = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    calgary_booth_options = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    calgary_options = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    calgary_date_1 = models.CharField(max_length=400, blank=True, default='-')
    calgary_date_2 = models.CharField(max_length=400, blank=True, default='-')
    calgary_date_3 = models.CharField(max_length=400, blank=True, default='-')
    calgary_additional_booth_option_1 = models.CharField(max_length=400, default='-')
    calgary_additional_booth_option_2 = models.CharField(max_length=400, default='-')
    calgary_additional_booth_option_3 = models.CharField(max_length=400, default='-')
    calgary_additional_lunch_option_1 = models.CharField(max_length=400, default='-')
    calgary_additional_lunch_option_2 = models.CharField(max_length=400, default='-')
    calgary_additional_lunch_option_3 = models.CharField(max_length=400, default='-')
    calgary_diet_request_1 = models.CharField(max_length=400, blank=True, default='')
    calgary_diet_request_2 = models.CharField(max_length=400, blank=True, default='')
    calgary_diet_request_3 = models.CharField(max_length=400, blank=True, default='')
    calgary_venue_options = models.CharField(max_length=255, blank=False, default='-')

class EdmontonFair(models.Model):
    related_sale = models.ForeignKey(SalesFormData, on_delete=models.SET_NULL, null=True)
    edmonton_dates = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    edmonton_booth_options = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    edmonton_date_1 = models.CharField(max_length=400, blank=True, default='-')
    edmonton_date_2 = models.CharField(max_length=400, blank=True, default='-')
    edmonton_date_3 = models.CharField(max_length=400, blank=True, default='-')
    edmonton_date_4 = models.CharField(max_length=400, blank=True, default='-')
    edmonton_additional_booth_option_1 = models.CharField(max_length=400, default='-')
    edmonton_additional_booth_option_2 = models.CharField(max_length=400, default='-')
    edmonton_additional_booth_option_3 = models.CharField(max_length=400, default='-')
    edmonton_additional_booth_option_4 = models.CharField(max_length=400, default='-')
    edmonton_additional_lunch_option_1 = models.CharField(max_length=400, default='-')
    edmonton_additional_lunch_option_2 = models.CharField(max_length=400, default='-')
    edmonton_additional_lunch_option_3 = models.CharField(max_length=400, default='-')
    edmonton_additional_lunch_option_4 = models.CharField(max_length=400, default='-')
    edmonton_additional_breakfast_option_1 = models.CharField(max_length=400, default='-')
    edmonton_additional_breakfast_option_2 = models.CharField(max_length=400, default='-')
    edmonton_additional_breakfast_option_3 = models.CharField(max_length=400, default='-')
    edmonton_additional_breakfast_option_4 = models.CharField(max_length=400, default='-')
    edmonton_diet_request_1 = models.CharField(max_length=400, blank=True, default='')
    edmonton_diet_request_2 = models.CharField(max_length=400, blank=True, default='')
    edmonton_diet_request_3 = models.CharField(max_length=400, blank=True, default='')
    edmonton_diet_request_4 = models.CharField(max_length=400, blank=True, default='')
    edmonton_venue_options = models.CharField(max_length=255, blank=False, default='-')

class WinnipegFair(models.Model):
    related_sale = models.ForeignKey(SalesFormData, on_delete=models.SET_NULL, null=True)
    winnipeg_dates = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    winnipeg_booth_options = models.CharField(max_length=400, blank=True, default='Value Determined By Checkbox')
    winnipeg_date_1 = models.CharField(max_length=400, blank=True, default='-')
    winnipeg_date_2 = models.CharField(max_length=400, blank=True, default='-')
    winnipeg_date_3 = models.CharField(max_length=400, blank=True, default='-')
    winnipeg_additional_booth_option_1 = models.CharField(max_length=400, default='-')
    winnipeg_additional_booth_option_2 = models.CharField(max_length=400, default='-')
    winnipeg_additional_booth_option_3 = models.CharField(max_length=400, default='-')
    winnipeg_additional_lunch_option_1 = models.CharField(max_length=400, default='-')
    winnipeg_additional_lunch_option_2 = models.CharField(max_length=400, default='-')
    winnipeg_additional_lunch_option_3 = models.CharField(max_length=400, default='-')
    winnipeg_diet_request_1 = models.CharField(max_length=400, blank=True, default='')
    winnipeg_diet_request_2 = models.CharField(max_length=400, blank=True, default='')
    winnipeg_diet_request_3 = models.CharField(max_length=400, blank=True, default='')